
steps:
  - name: gcr.io/cloud-builders/docker
    args: 
      - build
      - --tag=us-docker.pkg.dev/$PROJECT_ID/winecombr-devops/amazon-redshift-utils
      - .

images: 
  - 'us-docker.pkg.dev/$PROJECT_ID/winecombr-devops/amazon-redshift-utils'